---
extensions:
  - Details
  - DynamicPageList4
  - Scribunto
  - TemplateStyles
skins:
  - Femiwiki
config:
  Sitename: 페미위키
  FileExtensions: [png, gif, jpg, jpeg, webp, svg, pdf]
  LanguageCode: ko
  NamespacesWithSubpages:
    0: true
  DefaultSkin: femiwiki
  WikvenLogos:
    icon: symbol-transparent-white.svg
    svg: symbol-transparent-white.svg
    wordmark:
      src: logo-transparent-white.svg
      width: 142.93
      height: 44.61
  WikvenFooterUrl: https://github.com/femiwiki/femiwiki.github.io
  WikvenEditUrl: https://github.com/femiwiki/femiwiki.github.io/edit/main/$1
  WikvenHistoryUrl: https://github.com/femiwiki/femiwiki.github.io/commits/main/$1
  WikvenViewSourceUrl: https://github.com/femiwiki/femiwiki.github.io/blob/main/$1
  WikvenRepositories:
    Details:
      tarball: https://github.com/theapplewiki/mediawiki-extensions-Details/archive/refs/tags/1.2.1.tar.gz
      sha256: c1cd8bab8f02d10d5e179906711b4498ade75a9a1cc259f59d85d11638bacb7b
    DynamicPageList4:
      repository: https://github.com/Universal-Omega/DynamicPageList4
      commit: 7f2ef0ab84e99bf3f145afb328996e0858719d5d
    Femiwiki:
      tarball: https://github.com/femiwiki/FemiwikiSkin/releases/download/v5.1.2/v5.1.2.tar.gz
      sha256: 9d96a1fefb3ca404cca0a6381f1eb690a04a38266970946ced7644f7a77c3ad1
